[general]
live_config_reload = true
[window]
dynamic_padding = true
#opacity = 0.7
#blur = true

[font]
normal = {family = 'CaskaydiaMono Nerd Font Mono'}
size = 18

[cursor]
style = {shape = "Block", blinking = "Off"}

[keyboard]
bindings = [
{ key = "c", mods = "Control|Shift", action = "copy" },
{ key = "v", mods = "Control", action = "paste" },
]


# Colors (iTerm 2 default theme)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#2e2e2e'
red     = '#eb4129'
green   = '#abe047'
yellow  = '#f6c744'
blue    = '#47a0f3'
magenta = '#7b5cb0'
cyan    = '#64dbed'
white   = '#e5e9f0'

# Bright colors
[colors.bright]
black   = '#565656'
red     = '#ec5357'
green   = '#c0e17d'
yellow  = '#f9da6a'
blue    = '#49a4f8'
magenta = '#a47de9'
cyan    = '#99faf2'
white   = '#ffffff'
